defaults: &defaults
  machine: true

version: 2.0

jobs:
  install_and_build:
    <<: *defaults
    working_directory: ~/circleci-flaskphilo-sql
    steps:
      - checkout
      - run:
          name: Preparing env
          command: |
              pyenv install 3.6.3
              pyenv global 3.6.3
      - run: 
          name: Dependencies
          command: |
            git clone https://github.com/awslabs/git-secrets.git && cd git-secrets && sudo make install
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            #pip3 install -r ~/circleci-flaskphilo-sql/tests/tools/provision/requirements.txt
            cd ~/circleci-flaskphilo-sql && python3 setup.py install
            pip3 install flake8
       
      - run:
          name: Check Secret leak
          command: |
            git secrets --register-aws ; git secrets --add '\-{5}BEGIN\ RSA\ PRIVATE\ KEY-{5}' ; git secrets --scan --scan-history -r .

      - run:
         name: Running flake8
         command: |
            flake8 --exclude build,bin ./
      - run:
         name: Running Docker build
         command: |
            cd tests && docker-compose build

      - run: 
         name: Running tests
         command: |
            cd tests && python3 run_tests.py 

  deployment_production:
    <<: *defaults
    working_directory: ~/circleci-flaskphilo-sql
    steps:
      - checkout
      - run:
          name: Preparing env
          command: |
              pyenv install 3.6.3
              pyenv global 3.6.3
      - run:
          command: |
            pip3 install --upgrade setuptools
            sed -i "s/USER/$RIFF_USER/g" .pypirc 
            sed -i "s/PASS/$RIFF_PASS/g" .pypirc 
            sed -i "s/version=".*",/version=\'${CIRCLE_TAG}\',/" setup.py
            cp .pypirc ~
            python3 setup.py sdist upload -r pypi

workflows:
  version: 2

  build-only:
    jobs:
      - install_and_build:
          filters:
            branches:
              ignore:
                - dev
                - /feature\/.*
  build-and-deploy-production:
    jobs:
      - install_and_build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]*\..*/

      - deployment_production:
          requires:
            - install_and_build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]*\..*/
